version: '3.7'

services:
  # mariadb
  db:
    image: mariadb:10
    container_name: std-mysql
    restart: unless-stopped
    ports:
      - 3308:3306
    env_file: db.my.env
    volumes:
      - ./std-db/conf.d:/etc/mysql/conf.d
      - ./std-db/initdb.d:/docker-entrypoint-initdb.d
      - stdmydb_data:/var/lib/mysql # docker volume

  # postgresql
  # db:
  #   image: postgres:14
  #   container_name: std-pgsql
  #   restart: always
  #   env_file:
  #     - db.pg.env
  #   ports:
  #     - "5432:5432/tcp"
  #   volumes:
  #     - stdpgdb_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: std-mongo
    restart: always
    ports:
      - 27018:27017/tcp
    environment:
      MONGO_INITDB_ROOT_USERNAME: rupi
      MONGO_INITDB_ROOT_PASSWORD: rupi
    volumes:
      - stdmg_data:/data/db
      - stdmg_cfg:/data/configdb

  api:
    image: py39-slim
    container_name: std-api
    build: ./std-api
    # command: poetry run python app/main.py
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - api.env
    depends_on:
      - db
      - mongo
    links:
      - db
      - mongo
    ports:
      - 57000:8000
    volumes:
      - ./std-api/app:/backend/app
      - ./data:/data

volumes:
  # stdpgdb_data:
  #   name: stdpgdb_data
  stdmydb_data:
    name: stdmydb_data
  stdmg_data:
    name: stdmg_data
  stdmg_cfg:
    name: stdmg_cfg
